In [ ]:
!pip install gensim -q

from gensim.models import Word2Vec
from collections import Counter
import numpy as np

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, SimpleRNN, Dense

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 59.0 MB/s eta 0:00:00


#Part 1

In [ ]:
texts = [
    "AI is changing the world",
    "Machine learning is amazing",
    "Deep learning powers many applications",
    "I enjoy learning NLP",
    "NLP is fun and useful"
]

sentences = [text.lower().split() for text in texts]

##Task 1
Train a Word2Vec model using vector_size=30, window=2, min_count=1.


In [ ]:
w2v_model = Word2Vec(
    sentences=sentences,
    vector_size=30,
    window=2,
    min_count=1,
    workers=4,
    seed=42
)

##Task 2
Find the number of unique words and identify the most frequent word without printing the entire vocabulary.


In [ ]:
word_counts = Counter()

for sentence in sentences:
    word_counts.update(sentence)

print("Number of unique words:", len(word_counts))

most_common = word_counts.most_common(1)[0]

print("Most frequent word:", most_common[0])
print("Frequency:", most_common[1])

Number of unique words: 18
Most frequent word: is
Frequency: 3


##Task 3
Print the word vectors of any two words of your choice.


In [ ]:
print("Vector for 'learning':")
print(w2v_model.wv["learning"])

print("\nVector for 'applications':")
print(w2v_model.wv["applications"])

Vector for 'learning':
[-2.7383272e-02  1.8263733e-02  1.0304765e-02 -4.0747724e-03
 -4.4656517e-03  2.3906525e-02 -2.7603626e-02  1.3157869e-02
 -1.9902034e-02 -2.7054846e-02  1.7652630e-03  3.1708155e-02
  1.5716823e-02  1.7409313e-02  1.4498484e-02  1.9070951e-02
  8.8177127e-04 -2.4792425e-02  2.2649880e-02 -3.3076047e-03
  2.3460389e-05 -8.6134672e-03 -2.1163361e-02  2.8450998e-02
  1.8771164e-02  9.5910076e-03 -6.5057119e-03  2.1517439e-02
  3.0286075e-03 -3.7723898e-03]

Vector for 'applications':
[-0.02398505  0.00560653 -0.02702036  0.00998977  0.00858302 -0.02770371
  0.01716586 -0.00561284  0.01912576 -0.03055906 -0.02136957 -0.00040061
 -0.02078499 -0.01134259  0.0107066  -0.02369839  0.01184686 -0.02643981
 -0.02165432  0.00584297  0.01956555 -0.02196047 -0.01333382  0.02834134
  0.03264558  0.00540408 -0.00353079 -0.01020868  0.00749679  0.00606103]


##Task 4
Find the two most similar words to "learning".

In [ ]:
similar = w2v_model.wv.most_similar("learning", topn=2)

print("Two most similar words to 'learning':")

for word, score in similar:
    print(f"{word}: {score:.4f}")

Two most similar words to 'learning':
and: 0.2619
machine: 0.1460


##Task 5
Choose any two pairs of words, calculate their similarity, and briefly explain the results.


In [ ]:
similarity = w2v_model.wv.similarity("machine", "learning")

print(f"Similarity(machine, learning) = {similarity:.4f}")

Similarity(machine, learning) = 0.1460


#Part 2

In [ ]:
texts = [
    "I love AI",
    "AI is amazing",
    "I hate bugs",
    "Coding is fun",
    "This movie is terrible",
    "This movie is great"
]

labels = [1, 1, 0, 1, 0, 1]

##Task 1
Convert the text into sequences using TensorFlow Tokenizer and print only the sequences.


In [ ]:
tokenizer = Tokenizer()

tokenizer.fit_on_texts(texts)

sequences = tokenizer.texts_to_sequences(texts)

print("Sequences:")
print(sequences)

Sequences:
[[2, 6, 3], [3, 1, 7], [2, 8, 9], [10, 1, 11], [4, 5, 1, 12], [4, 5, 1, 13]]


##Task 2
Pad all sequences to the maximum sentence length in the dataset.

In [ ]:
max_length = max(len(seq) for seq in sequences)

padded_sequences = pad_sequences(
    sequences,
    maxlen=max_length,
    padding="post"
)

print(padded_sequences)

[[ 2  6  3  0]
 [ 3  1  7  0]
 [ 2  8  9  0]
 [10  1 11  0]
 [ 4  5  1 12]
 [ 4  5  1 13]]


##Task 3
Build a model with Embedding, SimpleRNN, and Dense output layers. Choose the embedding dimension and the number of RNN units yourself.


In [ ]:
vocab_size = len(tokenizer.word_index) + 1

embedding_dim = 16
rnn_units = 16

model = Sequential([
    Embedding(
        input_dim=vocab_size,
        output_dim=embedding_dim,
        input_length=max_length
    ),
    SimpleRNN(rnn_units),
    Dense(1, activation="sigmoid")
])

model.compile(
    optimizer="adam",
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn (SimpleRNN)          │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

##Task 4
Train the model for 15 epochs.


In [ ]:
history = model.fit(
    padded_sequences,
    np.array(labels),
    epochs=15,
    verbose=1
)

Epoch 1/15
1/1 ━━━━━━━━━━━━━━━━━━━━ 4s 4s/step - accuracy: 0.5000 - loss: 0.6998
Epoch 2/15
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.5000 - loss: 0.6926
Epoch 3/15
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.5000 - loss: 0.6855
Epoch 4/15
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.6667 - loss: 0.6785
Epoch 5/15
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 172ms/step - accuracy: 0.8333 - loss: 0.6715
Epoch 6/15
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step - accuracy: 0.8333 - loss: 0.6646
Epoch 7/15
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - accuracy: 0.8333 - loss: 0.6577
Epoch 8/15
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - accuracy: 0.8333 - loss: 0.6508
Epoch 9/15
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 215ms/step - accuracy: 0.8333 - loss: 0.6439
Epoch 10/15
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step - accuracy: 0.8333 - loss: 0.6369
Epoch 11/15
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step - accuracy: 0.8333 - loss: 0.6299
Epoch 12/15
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 166ms/step - accuracy: 0.8333 - loss: 0.62

##Task 5
Predict the sentiment of any two new sentences of your choice and explain whether the predictions are reasonable.


In [ ]:
new_sentences = [
    "I love swimming",
    "This exam is horrible"
]

new_sequences = tokenizer.texts_to_sequences(new_sentences)

new_padded = pad_sequences(
    new_sequences,
    maxlen=max_length,
    padding="post"
)

predictions = model.predict(new_padded)

for sentence, pred in zip(new_sentences, predictions):
    sentiment = "Positive" if pred[0] >= 0.5 else "Negative"
    print(f"{sentence} --> {sentiment} ({pred[0]:.4f})")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
I love swimming --> Positive (0.5330)
This exam is horrible --> Positive (0.5480)


predictions are reasonable because the words "love" and "coding" are associated with positive example, and "exam" and "horrible" are new

#Bonus

when increasing the embedding dimension for such a small dataset the accuracy drops

In [ ]:
#embedding dimension is changed.
embedding_dim = 32

bonus_model = Sequential([
    Embedding(
        input_dim=vocab_size,
        output_dim=embedding_dim,
        input_length=max_length
    ),
    SimpleRNN(16),
    Dense(1, activation="sigmoid")
])

bonus_model.compile(
    optimizer="adam",
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

bonus_model.fit(
    padded_sequences,
    np.array(labels),
    epochs=15,
    verbose=1
)

Epoch 1/15
1/1 ━━━━━━━━━━━━━━━━━━━━ 6s 6s/step - accuracy: 0.6667 - loss: 0.6822
Epoch 2/15
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - accuracy: 0.6667 - loss: 0.6691
Epoch 3/15
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 154ms/step - accuracy: 0.6667 - loss: 0.6564
Epoch 4/15
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.6667 - loss: 0.6440
Epoch 5/15
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.6667 - loss: 0.6318
Epoch 6/15
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - accuracy: 0.8333 - loss: 0.6198
Epoch 7/15
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.8333 - loss: 0.6080
Epoch 8/15
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.8333 - loss: 0.5965
Epoch 9/15
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.8333 - loss: 0.5850
Epoch 10/15
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.6667 - loss: 0.5738
Epoch 11/15
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.6667 - loss: 0.5627
Epoch 12/15
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.6667 - loss: 0.5517
Ep